calref/cboe

README.md
didn't seem to change anything last edit
=> Fixes to instructions

src/boe.startup.cpp
=> fixed a bug which caused the menu buttons to *sneeze*.

SConstruct, src/tools/cursors.linux.cpp, src/tools/winutil.linux.cpp
Added X11 to scons build script
Added debug argument to scons script
Used external program 'zenity' to handle file save/load dialogs
=> Small Update to Linux Branch

.gitignore, README.md, proj/vs2017/Blades of Exile.sln, proj/vs2017/Blades of Exile.vcxproj, proj/vs2017/Blades of Exile.vcxproj.filters, proj/vs2017/Character Editor/Character Editor.vcxproj, proj/vs2017/Character Editor/Character Editor.vcxproj.filters, proj/vs2017/Common/Common.vcxproj, proj/vs2017/Common/Common.vcxproj.filters, proj/vs2017/Installer/Installer.vcxproj, proj/vs2017/Installer/Installer.vcxproj.filters, proj/vs2017/Scenario Editor/Scenario Editor.vcxproj, proj/vs2017/Scenario Editor/Scenario Editor.vcxproj.filters, proj/vs2017/Tests/Tests.vcxproj, proj/vs2017/Tests/Tests.vcxproj.filters, proj/vs2017/Tests/stdafx.cpp, proj/vs2017/Tests/stdafx.h, proj/vs2017/Tests/targetver.h, proj/vs2017/Tests/unittest1.cpp, rsrc/menus/BladesOfExile.rc, src/fileio/debugout.win.cpp, src/game/boe.graphics.cpp, src/scenedit/scen.graphics.cpp, src/scenedit/scen.keydlgs.cpp
Tests and Install project are still WIP but shouldn't be a hold up to getting this merged.
I will move the vs2013 proj in another PR.
I am holding off on tests because I will work on MSTEST integration for both vs2013 and vs2017 in a different PR.
Install project in vs2017 is not a priority because as long as it still works in vs2013, @CelticMinstrel's workflow for creating releases will remain unaffected.
=> Adding vs2017 project in new proj directory parallel to src

src/game/boe.graphics.cpp, src/game/boe.graphutil.cpp, src/game/boe.main.cpp
All barriers that I could find are animated with this patch.
Fixes #214
=> Fix for barrier animation

src/game/boe.menu.hpp, src/game/boe.menus.linux.cpp, src/pcedit/pc.menus.linux.cpp, src/scenedit/scen.menu.hpp, src/scenedit/scen.menus.linux.cpp, src/tools/cursors.linux.cpp
As requested (if I understood correctly), I've changed all the #include statements necessary to make the CI branch compile on Linux. I think this may have touched more files than you (@CelticMinstrel) were anticipating, some of which didn't look linux-specific. So, maybe it won't get along with the CI of the other platforms. But fingers crossed.
=> make include paths absolute within src

src/game/boe.specials.cpp
Thanks @CelticMinstrel for helping figure this one out.
=> Fix #254 - ONCE_GIVE_ITEM

src/scenario/item.cpp, test/item_legacy.cpp
Fix a bug where flight-giving items didn't get a "use" button.
Also added unit tests.
=> Make flight ability usable outdoors

src/tools/vector2d.hpp
Tested and this doesn't break my Visual Studio 2017 build.
=> include cstddef to compile on linux

proj/vs2017/Common/Common.vcxproj
Fix #332 
Weirdly, things seem to run fine WITHOUT copying the data/ subfolders into the output directory. Does the resource manager embed them in the binary or something? Anyway, I made it copy them over anyway just in case.
=> vcxproj Copy scenarios and data to the right output dir

src/scenario/scenario.hpp, src/scenario/town.cpp, src/scenedit/scen.townout.cpp
=> Scenario editor initialize new town bounds/entrances

src/scenedit/scen.core.cpp
=> Fix underground starter scenario town terrain

src/game/boe.dlgutil.cpp
=> Only hide left/right buttons for empty vector

.github/workflows/ci.yml, .github/workflows/scripts/linux/install-tgui.sh, .github/workflows/scripts/win/install-deps.bat, .github/workflows/scripts/win/msvc-build.bat, .github/workflows/scripts/win/scons-build.bat, README.md, SConstruct, proj/vs2013/vcpkg.json, proj/vs2017/vcpkg.json, src/fileio/fileio_scen.cpp, src/fileio/resmgr/resmgr.hpp, src/scenedit/scen.core.cpp, src/scenedit/scen.fileio.cpp, src/scenedit/scen.keydlgs.cpp
I still can't get win-scons to work, but everything else is (usually), plus vcpkg dependencies cache now, which saves like 10 minutes per re-run.
=> Most builds fixed

src/dialogxml/dialogs/dialog.cpp, src/dialogxml/dialogs/dialog.hpp
The repetitive call to get_pref() is in an inline function now
=> naively scale dialogs by ui scale

proj/vs2017/Tests/Tests.vcxproj, proj/xc12/BoE.xcodeproj/project.pbxproj, proj/xc4/BoE.xcodeproj/project.pbxproj, src/fileio/tagfile.hpp, test/SConscript, test/map_read.cpp, test/map_write.cpp
This is a pull request because it probably requires changes to non-Xcode builds, so I want the CI to run.
=> Update Catch to v2.13.10

src/dialogxml/dialogs/dialog.cpp, src/dialogxml/widgets/field.cpp, src/game/boe.actions.cpp, src/game/boe.actions.hpp, src/game/boe.dlgutil.cpp, src/game/boe.dlgutil.hpp, src/game/boe.graphics.cpp, src/game/boe.infodlg.cpp, src/game/boe.main.cpp, src/game/boe.party.cpp, src/game/boe.startup.cpp, src/game/boe.text.cpp, src/game/boe.town.cpp, src/game/boe.town.hpp, src/location.cpp, src/location.hpp, src/pcedit/pc.editors.cpp, src/tools/replay.cpp, src/tools/replay.hpp
Starting to record and replay more things, mostly menu items and help buttons.
=> Record more

src/pcedit/SConscript
=> switch the order of 2 stupid things

src/game/boe.actions.cpp, src/game/boe.actions.hpp, src/game/boe.graphics.cpp, src/game/boe.main.cpp
=> Record extra

SConstruct
Here are a few more changes to `SConstruct` that I have in my release build branch, which should be harmless to the upstream CI build (but we'll see).
=> SConstruct changes

SConstruct, src/game/SConscript, src/pcedit/SConscript, src/scenedit/SConscript, test/SConscript
=> Fix #444: win-scons include Visual Studio debug symbols

CONTRIBUTING.md, README.md
Update README/CONTRIBUTING to reflect the more current practices for this project.
=> update README and CONTRIBUTING.md

rsrc/dialogs/edit-item-shortcut.xml, rsrc/dialogs/edit-outdoor-encounter.xml, rsrc/dialogs/edit-special-item.xml, rsrc/dialogs/edit-town-details.xml, rsrc/dialogs/make-scenario1.xml, rsrc/dialogs/make-scenario2.xml, rsrc/dialogs/new-town.xml, rsrc/dialogs/pc-alchemy-info.xml, src/dialogxml/dialogs/strchoice.cpp, src/pcedit/pc.editors.cpp
I've gone through all the files that my grep pattern identified as having textless `led` elements (#297). This should fix all of them, and close #297.
That is unless `led`s are created programatically anywhere in the codebase. But if they all have to be declared in xml then I think I can guarantee I changed them all.
=> Fix led labels

.github/workflows/ci.yml, SConstruct, src/tools/SConscript
When finished this will close #514
=> Fix win-scons CI

src/game/boe.actions.cpp, src/game/boe.consts.hpp, src/game/boe.dlgutil.cpp, src/game/boe.graphics.cpp, src/game/boe.main.cpp, src/game/boe.newgraph.cpp, src/game/boe.newgraph.hpp
Fix #566
Fix #567 
Fix #86
EDIT: Also Fix #64
=> Fix UI bugs in shopping

src/game/boe.actions.cpp
=> Disallow deleting PC in combat. Fix #70

rsrc/bases/bladbase/items.xml, rsrc/scenarios/busywork/items.xml, rsrc/scenarios/stealth/items.xml, rsrc/scenarios/valleydy/items.xml, rsrc/scenarios/zakhazi/items.xml
As requested, submitting a PR to update typos on this branch. Hopefully this was done correctly... greenhorn collaborator. Feedback welcome.
=> Fixed typos for Resurrection Balm and Leather Baldric.

src/scenedit/scen.core.cpp
=> Select monster current attack type. Fix #145

src/game/boe.actions.cpp, src/game/boe.main.cpp
Fix #589 and 1 other bug, plus make the message better when player tries to save during combat.
=> Basic fixes

doc/documentation.lyx, doc/game/Priest.html, doc/game/Tips.html, doc/game/Town.html, rsrc/strings/alchemy.txt, rsrc/strings/help.txt, rsrc/strings/pcedit.txt, rsrc/strings/priest-spells.txt, rsrc/strings/tips.txt
I found more pronouns that can be simplified.
=> His/her -> their, He/she -> they

.gitignore, rsrc/dialogs/kill-party-confirm.xml, src/game/boe.actions.cpp, src/game/boe.actions.hpp, src/game/boe.main.cpp
I tested that this does not bring back the scrollbar bug. Fix #597
=> Fix restore

src/dialogxml/dialogs/dialog.cpp, src/dialogxml/dialogs/dialog.hpp, src/dialogxml/dialogs/strdlog.cpp, src/dialogxml/dialogs/strdlog.hpp, src/game/boe.actions.cpp, src/game/boe.actions.hpp, src/game/boe.combat.cpp, src/game/boe.dlgutil.cpp, src/game/boe.infodlg.cpp, src/game/boe.infodlg.hpp, src/game/boe.items.cpp, src/game/boe.main.cpp, src/game/boe.party.cpp, src/game/boe.text.cpp, src/pcedit/pc.editors.cpp, src/pcedit/pc.main.cpp, src/universe/pc.cpp, src/universe/pc.hpp
This resolves a TODO note explaining a bug I've confirmed and fixed.
=> Fix a help dialog that appears in the top-left

src/dialogxml/dialogs/strdlog.cpp, src/dialogxml/dialogs/strdlog.hpp, src/game/boe.main.cpp, src/pcedit/pc.main.cpp, src/scenedit/scen.main.cpp, src/scenedit/scen.townout.cpp, test/catch.cpp
Adding a global variable when I know we want to have less of them. 😬
=> DRY advanced town help. Fix #611

src/game/boe.items.cpp, src/game/boe.specials.cpp, src/game/boe.specials.hpp, src/global.hpp, src/scenedit/scen.keydlgs.cpp
I really didn't like the get_strs() function in boe.special.cpp which always had to get 2 strings at a time even if you only needed 1 or were going to need 6 total. I made all that code DRY and less horrifying.
I also fixed some crash bugs in various string dialogs.
=> Spec strings

rsrc/dialogs/edit-sign.xml, rsrc/schemas/dialog.xsd, src/dialogxml/widgets/message.cpp, src/doxy/mainpage.md
=> handle showPipes in code only. Fix #609

src/game/boe.actions.cpp, src/game/boe.consts.hpp, src/game/boe.newgraph.cpp
Alternative PR to #627. If you like this better you can take this and close the other.
Fix #624
=> Add hotkey in top-left corner of shop item. Fix #624

src/universe/party.cpp
It appears this fix is incredibly simple. Am I missing anything?
Fix #621
=> Write timer index. Fix #621

src/game/boe.graphutil.cpp
Wow... I made a pretty silly mistake in #631 which turned the party invisible in the outdoors. This is the fix.
=> Fix party invisible outdoors

src/game/boe.graphics.cpp
=> Fix momentarily disappearing scrollbar

.github/workflows/ci.yml, .github/workflows/scripts/win/scons-build.bat, README.md, SConstruct, pkg/win/build-scen.bat, src/dialogxml/widgets/stack.cpp
=> Fix scenario picker, update README & build script

SConstruct, src/tools/SConscript, test/SConscript
This should get the CI scons builds working
=> Format fix
