src/dialogxml/dialog.cpp
Celtic Minstrel and I figured out that windows created immediately after another don't have trouble refreshing or updating their content... so... it now creates a window, closes it before it has time to render, and then create the one we want. 
Please don't hit me.
=> Partial solution for UI refresh error

src/tools/winutil.mac.mm
* Allow selection of files that only have an HFS file type.
* Use `-[NSString fileSystemRepresentation]` when passing the contents of `NSString`s to lower-level file APIs.
=> Improve winutil.mac.mm

src/game/boe.town.cpp, src/game/boe.town.hpp, src/scenario/area.hpp, src/scenario/scenario.cpp, src/scenario/scenario.hpp, src/scenario/special.hpp
This cleans up the `erase_out_specials()` method in `boe.town.cpp` and introduces a few new helper methods.
Also introduces a minor fix on what is now `erase_completed_specials()` where we weren't ensuring the index did not exceed the vectors elements;
=> Erase specials refactor

SConstruct
`build/pkg/SConscript` only exists for darwin or for win32 when makensis is available, so it should not be added inconditionally.
Without this patch it triggers this warning on posix:
```
scons: warning: Ignoring missing SConscript 'build/pkg/SConscript'
```
=> SCons: Fix warning on posix build

src/scenario/monster.cpp
Previous code would raise this error with GCC 5.5.0:
```
build/obj/scenario/monster.cpp:804:19: error: use of 'abil' before deduction of 'auto'
for(auto& abil : abil) {
^
```
I'd advise to do some further refactoring to prevent confusion between the public `abil`
which is a map of two types of abilities, and the various local `abil`s that shadow it
in monster.cpp.
=> Fix GCC build issue with ambiguous for loop iterator

src/game/boe.combat.cpp, src/game/boe.party.cpp, src/game/boe.party.hpp, src/game/boe.specials.cpp, src/game/boe.specials.hpp
Return actual damage done from damage_monst and damage_pc and print that instead of raw (pre-armor) values that are printed currently.
Fixes #248
=> Fix incorrect damage values in transcript

SConstruct
Removed scons checks for boost thread library as well as the related linker flag.
=> remove usage of boost threads in SConstruct

src/universe/universe.hpp
Upon loading a save, a new instance of universe is default-constructed and then moved into existing universe. The problem is that several boolean flags in universe do not have initializers, so they sometimes end up with garbage values.
Fixes #198 
Fixes #200
=> Fix debug mode (and other universe flags) being randomly set on upon load

src/game/boe.actions.cpp, src/game/boe.consts.hpp, src/game/boe.dlgutil.cpp, src/game/boe.newgraph.cpp, src/game/boe.newgraph.hpp
* Fixed unclickable shop icons by applying the same offset to event catching rects as is applied to the shop UI when it's being drawn in the main window.
* Removed strange adjustment of mouse click coords in shop UI by (-5, -5) px.
* Removed click_shop_rect function that was doing "click emulation" in shop UI. Rationale: 1) it was causing visual glitches, because 2) various widgets do not get to decide when .display() is called, since other drawables may not be ready
* Removed unneeded shop scrollbar redraw call which may improve performance of that UI a bit
Fixes #247
=> Fix unclickable shop info icons

src/game/boe.menu.cpp, src/game/boe.menu.hpp, src/pcedit/pc.menu.hpp, src/scenedit/scen.menu.hpp, src/tools/winutil.hpp
These are the changes I had to make to compile against TGUI 0.9.1 (the version available in the Arch Linux user repository, AUR).
The main thing is that TGUI uses its own String class now instead of SFML's.
This should fix #284 .
I had to trigger the build with `scons INCLUDEPATH=$HOME/repos/cboe/deps/Catch2/include`. I thought it shouldn't be necessary to pass that INCLUDEPATH manually (and as an absolute path) when Catch2 is meant to be provided as a submodule by default, but that should probably be a separate issue.
Locally, the scons build ran without error and told me All tests passed. The game launches and I've created a party and opened a scenario successfully.
=> Update to TGUI 0.9.x

src/dialogxml/dialogs/dialog.cpp, src/dialogxml/dialogs/dialog.hpp, src/game/boe.main.cpp
Provides a partial fix for #208.
Based on this thread [here](https://en.sfml-dev.org/forums/index.php?topic=19658.0) it seems that SFML doesn't track an event for window movement. However, it tracks mouse movement and provides `RenderWindow.getPosition()`. So this patch tracks whether `win.getPosition()` reports a new position after a mouse movement event in cDialog. If the position has changed, it calls `redraw_everything()` and this fixes the artifacts left by dragging the dialog.
It's a little janky, but I've made a function pointer for `redraw_everything` in the cDialog class so that function can be provided in `boe.main.cpp` -- since it doesn't exist yet at cDialog's compile-time.
This is only a partial fix. It does not redraw over the artifacts left if the player drags the zenity …
=> call redraw_everything() when cDialogs move

SConstruct, src/fileio/tagfile.hpp, src/tools/SConscript, test/SConscript
Actually does 2 things.
1: Fix the tagfile `#include <memory>` error, and also the linker error from tagfile.cpp not copying into build/obj.
2: Fix the Scons process so it copies Catch2 into build/obj/test/deps like we discussed in IRC.
=> Fix tagfile error

src/fileio/resmgr/res_dialog.cpp, src/fileio/resmgr/res_dialog.hpp, test/dialogs.cpp
This test case should catch potential regressions of #273.
cDialog prepends data/dialogs onto the path you pass it, so I had to add an optional flag to not do that, so the tests can pass a path relative to their cwd.
=> Test case for dialog XMLs

src/tools/winutil.linux.cpp
I started trying to change the return type to boost::optional, but that turned out to be a lot of work and I realized the if statements would then have to check the optional for existence AND check the value for non-emptiness, which would just be silly.
=> Linux handle zenity non-zero code. Close #301

src/tools/winutil.win.cpp
I built the game on Windows and found that I actually couldn't reproduce #268 -- because it seems that dlg.lpstrFile is actually an empty string in the case of a cancel or an error. At least, when built with Visual Studio 2017, that was the case when I debugged it a few times.
Maybe it's not guaranteed that lpstrFile will be an empty string, and random behavior caused this bug. I've added a commit that sets it to an empty string, which will guarantee that doesn't happen.
This, unlike my previous PR, also avoids leaking memory by following the same control flow as before.
This should close #268.
=> Make sure lpstrFile is empty on cancel

src/scenedit/scen.townout.cpp
Simple fix for the first crash reported in #244.
Fixes for the second crash turned into a rabbit hole so I'll make them a separate, bigger PR.
=> Don't crash when canceling scenario import pick

rsrc/dialogs/edit-scenario-events.xml, src/dialogxml/dialogs/dialog.cpp, src/scenedit/scen.core.cpp
Still in progress--this PR will fix the second crash reported in #244 by adding an extra page of scenario event timers in the scenario editor so all 20 can be used.
The first 2 commits, cc18c56866fa0c90239789eb39c0ba4b931b0825 and 1c775da7d2fec3b711861bd4396e3a1181191cf4, fix bugs in cDialog that caused other issues which I didn't open tickets for:
1) text field controls inside stack widgets didn't become focused when clicked on. The tab key was the only way to focus them.
2) entering characters to a text field in a stack widget would cause a crash.
Those bugs could be observed by editing town details and trying to edit the 3 comment fields which are managed by a stack.
=> [WIP] Fix 244b

proj/vs2017/Common/Common.vcxproj, src/fileio/fileio_scen.cpp, src/fileio/xml-parser/tinyxmlparser.cpp, src/scenario/outdoors.hpp, src/scenario/shop.hpp, src/universe/party.cpp, test/tagfiles.cpp
- The new version of tinyxml uses [[fallthrough]] declarations that only serve to suppress a warning and require c++17 so I commented them out: https://en.cppreference.com/w/cpp/language/attributes/fallthrough
- This modification should be fine according to Tinyxml's MIT license, which I don't think requires adding a notice that it's modified.
- For some reason the `#undef INFINITE` directive isn't working. I figured renaming the constant could be a suitable alternative.
=> Fix visual studio build

src/universe/party.cpp
After finding that #324 was due to swap() getting called twice, I figured out why the double-call was happening. For some reason, making the argument to the cUniverse copy constructor a reference and not a double-reference averts the bug. The double-reference looked wrong to me anyway, so maybe this is a correct solution.
=> Fix swap() double-call

.gitignore, .gitmodules, README.md, SConstruct
This is the last PR, with submodules instead of subtrees, and a few more things:
* add Catch2 dependency to the README
* partial build options
* correct debug flags on all platforms
* when scons -c is called, print a note about deleting .sconsign.dblite (this addresses #330, which I still can't reliably fix, but deleting the file manually works every time)
=> Local build improvement redo

src/dialogxml/dialogs/dialog.cpp, src/dialogxml/dialogs/dialog.hpp, src/dialogxml/dialogs/strdlog.cpp, src/game/boe.appleevents.mm, src/game/boe.main.cpp, src/game/boe.main.hpp, src/game/boe.menus.linux.cpp, src/game/boe.menus.win.cpp, src/pcedit/pc.appleevents.mm, src/pcedit/pc.main.cpp, src/pcedit/pc.menus.linux.cpp, src/pcedit/pc.menus.win.cpp, src/scenedit/scen.appleevents.mm, src/scenedit/scen.main.cpp, src/scenedit/scen.menus.linux.cpp, src/scenedit/scen.menus.win.cpp
It turns out that on Windows, you could launch with a save file loaded by passing that save file as a command-line argument. But only on Windows, because this functionality was implemented in a platform-specific implementation of `set_up_apple_events()` which seems wrong on many levels.
It turns out, this could also lead to a silent crash if you tried to launch BoE with a party file, and the loading failed. `load_party()` would try to call `showError()`, which relies on the UI being initialized. This would crash.
So I modified `showError()` to check if UI is initialized. If it's not, it just prints the error to console instead.
Once that was fixed, I figure we want all platforms to support the same command-line launch arguments, so I moved that logic out of the Windows-only file and into …
=> Fix silent crash on Windows & Standardize command line arguments

pkg/mac/BoE-Info.plist, pkg/mac/BoECharEd-Info.plist, pkg/mac/BoEScenEd-Info.plist
Fixes #369 in a counterintuitive way.
I would have thought that we would want the flag that says High DPI displays *are* supported (which was even something [Fosnola](https://github.com/calref/cboe/pull/346/commits/ff05298ebec161cded8b8aa0821b4879bd0b9954) had done and I tried cherry-picking to fix this.)
But this [very old SFML forum thread](https://en.sfml-dev.org/forums/index.php?topic=17241.msg124542#msg124542) suggested setting the very same flag to false. Which I did, and it fixed both parts of the issue--the fullscreen window size, and the positioning of dialog windows.
=> Fix fullscreen window sizing on MacOS HighDPI display

SConstruct
My Mac installed homebrew libraries into /opt/homebrew, not /usr/local, so the scons build didn't work for me locally without this change. I also had to point it to sfml.
=> More homebrew search paths in Mac Scons

src/game/boe.graphics.cpp, src/game/boe.graphics.hpp, src/game/boe.menus.win.cpp, src/game/boe.startup.cpp, src/pcedit/pc.main.cpp, src/pcedit/pc.menus.win.cpp, src/scenedit/scen.main.cpp, src/scenedit/scen.menus.win.cpp, src/tools/winutil.hpp, src/tools/winutil.linux.cpp, src/tools/winutil.mac.mm, src/tools/winutil.win.cpp
Fixes #366 
This bug was unbelievably hard to track down and fix.
I think it was probably caused by a change in SFML's code for handling window resize events on Windows. When we add the menubar to the window by bypassing SFML and using the Windows APIs, SFML now detects that change and shrinks the logical viewport of your window without expanding the window itself to fit the menubar in it.
I updated `menuProc()` to catch that first unwanted resize event and discard it. I also made the window expand to fit the menubar's additional height, handled for a rare edge case where the menubar needs more than 1 row for its buttons, and made sure the splash screens still render in the right places.
I need to test this on Linux and Mac to make sure it didn't break those.
=> Fix graphics flickering/stretching on Windows

src/dialogxml/dialogs/dialog.cpp, src/dialogxml/widgets/control.cpp, src/dialogxml/widgets/control.hpp
I saw a couple of repetitive things in cControl and cDialog, one of which was marked with a TODO to deduplicate it.
In the first case, I simply made a function and changed the 2 repetitive places to call the function.
The second case was more complicated, and my change actually does change the behavior, but I don't think it should matter unless any widgets have containers in containers and we want those *not* to be processed recursively (how it was before).
=> Fix some repetitive code in dialogs

SConstruct
I discovered a scons error on Mac when you try to do a partial build without first doing a full build of all targets. This fixes it
=> mac don't try to install resources to excluded partial build targets

src/dialogxml/widgets/container.cpp, src/game/boe.actions.cpp, src/game/boe.actions.hpp, src/game/boe.appleevents.mm, src/game/boe.main.cpp, src/game/boe.main.hpp, src/tools/replay.cpp, src/tools/replay.hpp
2 core changes:
* I moved the replay_next_action() call into the actual game loop and only process one action per frame, so things actually redraw in between actions.
* Fixed replaying control clicks inside subclasses of cContainer (so cStack and cScrollPane), which had the same problem that led groups previously had
Aside from that, added recording and replay for several relatively trivial actions.
=> Replay System part 3

src/tools/winutil.win.cpp
This fixes #327 for Windows, and I've seen that on Mac it wasn't a problem. Need to see how Zenity handles this on Linux, though
=> Fix #327 for windows

rsrc/SConscript
On my linux installation `which xmllint` returns 0 but the output is empty (because I don't have xmllint). This PR fixes the logic so scons won't keep trying to lint the xml when I do my linux builds
=> fix xmllint check in SConscript

src/dialogxml/dialogs/dialog.cpp, src/dialogxml/keycodes.cpp, src/dialogxml/keycodes.hpp, src/game/boe.actions.hpp, src/game/boe.main.cpp, src/game/boe.main.hpp, src/game/boe.startup.cpp
Since there is the one case where a modifier key is relevant in the startup menu, I figure we should handle the modifier keys in the same way dialogs do, because this makes it easier to record and replay that edge case.
=> record and replay mods on startup buttons. fix #394

src/mathutil.cpp
Fixes #407 and presumably many other pernicious bugs
=> fix get_ran() returning out-of-bounds negatives

src/dialogxml/dialogs/dialog.cpp, src/dialogxml/dialogs/dialog.hpp, src/dialogxml/widgets/button.cpp, src/dialogxml/widgets/container.cpp, src/dialogxml/widgets/container.hpp, src/dialogxml/widgets/control.cpp, src/dialogxml/widgets/control.hpp, src/dialogxml/widgets/field.cpp, src/dialogxml/widgets/field.hpp, src/dialogxml/widgets/led.cpp, src/dialogxml/widgets/ledgroup.cpp, src/dialogxml/widgets/ledgroup.hpp, src/dialogxml/widgets/message.cpp, src/dialogxml/widgets/message.hpp, src/dialogxml/widgets/scrollbar.cpp, src/dialogxml/widgets/scrollbar.hpp, src/dialogxml/widgets/scrollpane.cpp, src/dialogxml/widgets/scrollpane.hpp, src/game/boe.actions.cpp, src/game/boe.actions.hpp, src/game/boe.dlgutil.cpp, src/game/boe.dlgutil.hpp, src/game/boe.main.cpp, src/game/boe.main.hpp, src/game/boe.menus.hpp, src/game/boe.startup.cpp, src/gfx/render_text.cpp, src/gfx/render_text.hpp
This rebases the first set of changes in #397:
* Get CPU usage down from 100% during splash screens and control clicks
* Make text line-wrapping cacheable, and cache the wrapping for cTextMsg
A couple of things to do before merging:
~~- [ ] Make other callers of `win_draw_string()` cache their line breaks, where applicable~~ (in a later PR)
As far as I know, this would solve the only CPU-hogging component of the DialogXML system, thus fixing #227
=> Fix cpu rebase

SConstruct, proj/vs2017/Blades of Exile.vcxproj, proj/vs2017/Character Editor/Character Editor.vcxproj, proj/vs2017/Common/Common.vcxproj.filters, proj/vs2017/Scenario Editor/Scenario Editor.vcxproj, proj/xc12/BoE.xcodeproj/project.pbxproj, proj/xc12/BoE.xcodeproj/xcshareddata/xcschemes/Blades of Exile.xcscheme, src/game/boe.main.cpp, src/pcedit/pc.main.cpp, src/scenedit/scen.main.cpp, src/tools/cli.hpp, src/tools/framerate_limiter.cpp, src/tools/framerate_limiter.hpp, src/tools/replay.cpp, src/tools/winutil.hpp, src/tools/winutil.linux.cpp, src/tools/winutil.mac.mm, src/tools/winutil.win.cpp
This makes use of the Clara command-line library included with Catch to do proper parsing of command-line arguments.
This fixes an issue where the scenario editor complains about a missing file when launched from Xcode, because Xcode passes an unrecognized argument which is interpreted as a filename. The Clara parser seems to ignore unrecognized arguments, so using it makes this work. It does unfortunately require using flag syntax instead of subcommand style for the replay system.
If this looks mostly okay, it might be better to update to the Lyra library instead, which is similar in substance but is still being maintained. Unlike Clara, Lyra has support for subcommands, so we wouldn't need to change the existing command-line syntax. I don't know if it ignores unrecognized arguments like …
=> WIP Command-line reform

src/game/boe.actions.cpp, src/game/boe.main.cpp
Partly implemented fix for arrow key handling on mac, which also introduces a frame buffer for arrow key combinations that would solve #225.
The problem now is that diagonals formed by two arrow keys, don't repeat properly. So I'm trying to disable key repeating when diagonals are used, and turn it back on in other cases. Which is just messy and not good. Needs more tinkering.
=> fix #405 and fix #225

SConstruct
Fix the use-case where header files are put directly in deps/include, which was straight-up broken
=> Fix include path in SConstruct

SConstruct
The first commit here is probably superfluous, but technically makes SConstruct more correct.
The second commit fixes a bug where `.framework` libraries in `deps/lib` wouldn't be copied into the app bundle.
=> Change framework bundling

.github/workflows/scripts/mac/scons-build.sh, .github/workflows/scripts/win/scons-build.bat
In my release build github action, the workflow yaml file calls `scons-build.sh` and `scons-build.bat` with additional arguments that we don't want in those files directly. To enable this, I've modified the two scripts to forward all of their arguments to `scons` itself. This should change nothing in the upstream CI, but will make my life easier maintaining a release build branch that's easy to rebase with the upstream.
=> forward the args from platform-specific scons scripts

SConstruct, pkg/gitrev.sh, proj/vs2013/Common/Common.vcxproj, proj/vs2017/Common/Common.vcxproj, src/tools/replay.cpp
Close #440 
I found a bug where scons builds defined GIT_TAG as empty because of a trailing blank line in the subprocess output.
Fixed that, and am now recording a root element like this:
```
<actions SHA="f411a46" Tag="v0.0.4" Status="modified" Repo="git@github.com:NQNStudios/cboe.git">
```
The CI will show whether my changes to `gitrev.sh` work for the Xcode build.
=> Record version info

.gitmodules, SConstruct, pkg/mac/fix_dylibs.sh
This adds a 1-file submodule which just contains my python script that detects and fixes broken rpath/dependency references in the app bundles. And extends SConstruct to make sure the submodule is cloned, and call the script automatically.
This theoretically would have fixed the problems behind #192 although the script might not cover every possible edge case.
=> Fix rpaths

test/SConscript
This fixes a test case I wrote years ago which has been silently failing for scons builds.
An upcoming PR will remedy the fact that those failures have been silent--but I haven't yet fixed *other* things which fail besides this.
=> Fix my dialog construction test case's file loading

.github/workflows/ci.yml, .github/workflows/scripts/linux/scons-build.sh, test/SConscript
I've been trying to pave the way for #441 by making the scons ci builds fail when the tests fail.
This proved troublesome because the Linux and Win-Scons builds have been failing the tests silently for quite a while.
For some reason, Linux needs an X server to run the tests -- this was a pretty trivial fix because a utility is included on Ubuntu github actions runners called `xvfb` which I had never heard of but seems really awesome. It runs a headless X server for CI workflows. Using this fixed that problem.
(Note for the future: there's a github action that lets you use `xvfb` on Windows and Mac. Maybe we could someday even be running our full replay test suite on CI for all three platforms this way. I don't know how sophisticated it is.)
Now, for win-scons the tests are failing with an …
=> Fix scons tests

src/tools/winutil.linux.cpp
As talked about in #373, here's an error message on Linux explaining that zenity needs to be installed if it isn't.
=> linux zenity installation message

SConstruct
When built from source on Windows, zlib comes out as `zlibd.dll` for debug builds. This adds support for that case.
=> d is the debug suffix for zlib built from source

SConstruct
At this point I'm using my own from-source builds to supply pretty much all of the dependencies in my local builds. This is another fix for that case, which hopefully won't affect the CI case.
Setting up another Windows dev environment I was getting a frustrating bug--Boost has some kind of "auto-link" feature which causes it to try to link against a DLL which doesn't exist in my from-source builds and isn't passed as a link flag. The only way to stop this is to define `BOOST_ALL_NO_LIB`.
=> fix boost auto-link breaking some win scons builds

README.md
Could be made more concise, and might not be git beginner-friendly enough, but I made some edits that should make our recurring problem stated in #462 less common by being extremely explicit and using bold/capitalized text and a heading.
=> Update README.md to address #462

src/game/boe.startup.cpp, src/tools/keymods.cpp, src/tools/keymods.hpp
This fixes #476 in the most direct way possible, without understanding the underlying cause which seems to be at the SFML/MacOS level.
=> Fix #476 directly

src/game/boe.actions.cpp
Something that's been janky for a while is that the overworld state doesn't redraw just before outdoor combat starts, so it looks like the monster is still 1 square away from you when logically you're touching, which triggers the fight. This leads to possible instances of #237 but might not be the only explanation for that bug.
Anyway, a pretty simple fix added the visual clarity we want.
=> render the frame that triggers outdoor combat

src/game/boe.newgraph.cpp
Making a small arbitrary width adjustment to word rectangles fixes #481. I can't think of any negative side effects to this and I can't think of a reason to search for a more sophisticated solution.
=> Fix word highlight

src/game/boe.town.cpp
I was looking to fix #487 and #428. While I was doing that, I looked through the call sites of `clear_map()` and found that nearly every call was used in a context where we wanted to *redraw* the map, not clear it. We only really want the "clear" behavior of clear_map() once, when the texture is initialized pure white and we want it black instead.
It turns out that modifying `clear_map()` so it calls `draw_map(true) fixes #487, and fixes #428 in one fell swoop. For whatever reason, clear_map() seems to be a misnomer.
I think draw_map() short-circuits safely if nothing can be drawn (i.e. the initialization "fill the new texture with black" case), and if that's correct, this is a simple fix.
I have a hunch that #267 was a manifestation of this bug too--because I've never reproduced the …
=> clear_map() call draw_map() after

src/dialogxml/dialogs/dialog.cpp, src/dialogxml/widgets/control.cpp, src/dialogxml/widgets/field.cpp, src/dialogxml/widgets/scrollbar.cpp, src/game/boe.actions.cpp, src/game/boe.main.cpp, src/game/boe.specials.cpp, src/game/boe.startup.cpp, src/game/boe.ui.cpp, src/pcedit/pc.main.cpp, src/scenedit/scen.graphics.cpp, src/scenedit/scen.main.cpp, src/tools/winutil.cpp, src/tools/winutil.hpp
This was meant to address #476 but doesn't actually solve the problem. Still might be a good change, though--
We're calling pollEvent on a lot of windows all over the place, and I see a lot of places (maybe only for a few frames, but still) where events never seem to reach `kb.handleModifier()` which is crucial for not letting modifier key state get stuck on MacOS.
So I wrapped pollEvent(), and if we always use the wrapper, handleModifier() will always be called.
=> wrap pollEvent() to guarantee all loops handle modifiers

SConstruct, src/game/SConscript, src/pcedit/SConscript, src/scenedit/SConscript, test/SConscript
I think any developer is going to want their default build to be debug. I'm often frustrated that I can't see a crash's callstack while testing because I accidentally built release.
I replaced the `debug` flag with a `release` flag, default false. When the `debug` flag is passed, it is ignored and a warning is printed explaining the change. Supporting both a `debug` and a `release` flag required to be opposite values was a nightmare, I tried.
Bonus: All unknown options will print a warning. I'm constantly doing `scened=true` instead of `scenedit=true` etc and this should help.
=> make scons build debug by default

README.md
It is a little confusing that the Readme says "Classic Blades of Exile". When I was looking for builds many years ago that was something that tripped me up. Is it significant? If not, maybe we should change it. Everywhere else, we already say Blades of Exile or Open Blades of Exile.
=> Update Readme to reduce confusion

src/game/boe.newgraph.cpp
Fix #493 
Fosnola had fixed part of the light mask visual errors having to do with the offsets for the overall rectangle and the ellipses.
<details> 
<summary>Before</summary>
</details>
After:
In my opinion there are still some oddities in the light mask system (see #509), but this is an absolute improvement and the other problems are much more complicated, so this should just go in.
=> Fix lighting

src/game/boe.actions.cpp, src/game/boe.actions.hpp, src/game/boe.main.cpp, src/game/boe.town.cpp
Look and talk targeting can be canceled now.
Escape will cancel any mode targeting in progress.
And since re-typing a letter cancels everything else, I made the map act the same ('a' to toggle)
=> Cancel look & talk targeting modes. Escape key to cancel anything.

pkg/credits/about-boe-template.xml, rsrc/dialogs/about-boe.xml, rsrc/dialogs/about-pced.xml, rsrc/dialogs/about-scened.xml, src/game/boe.graphics.cpp, src/scenedit/scen.actions.cpp
With permission, I've changed the Copyright notices to say "Created 1997, Free Open Source" which I think will make things seem more welcoming as opposed to "All Rights Reserved".
Removed pricing/how to order messages.
Replaced old contact info with links to the repo's issue tracker.
Made about-pced.xml and about-scened.xml use relative positioning
Close #499
=> Update copyright notices and contact/pricing info.

src/game/boe.actions.cpp, src/game/boe.actions.hpp, src/game/boe.consts.hpp, src/game/boe.graphics.cpp, src/game/boe.startup.cpp
This creates the arrangement decided on in #173 and takes the first steps to implementing the tutorial.
=> Rearrange startup buttons, add tutorial button with stub event

src/game/boe.graphics.cpp, src/global.hpp
I'm constantly typing the same debug boilerplate:
`std::cout << "var: " << var << std::endl;`
It gets ridiculous and I really want to reduce keystrokes because my wrists hurt.
I found that you can simplify this with a preprocessor macro. It works with variables, and also arbitrary expressions, which is cool. I called that macro LOG_VALUE and put it in global.hpp.
For a similar purpose, I made a global function that logs a line of text (std::string) and I named it LOG (uppercase to match the macro--I think it just makes sense to have temporary log statements jump out at you when reading/diffing code.)
=> LOG function and LOG_VALUE macro will save time and wrist exertion

src/game/boe.main.cpp, src/tools/replay.cpp
* Makes the replay system `exit(1)` with an error message if it can't initialize the action log.
* Refactor the `replay_next_action()` function so we could theoretically pass arbitrary generated actions, or store actions from `pop_next_action()` to process out of order.
* Allow recording a session that starts with loading a party from CLI
=> Replay system improvement/refactor

src/game/boe.dlgutil.cpp
Creating a new scenario in the current editor and giving it a shop, the editor defaults the extra D flag to something that would have been invalid back when shops weren't unified under one node type.
This should be fine, but the check for a valid D value was left in. So any shop created in the current editor would throw an error despite being valid. I removed the check.
=> D flag for shops is now ignored

src/dialogxml/dialogs/pictchoice.cpp, src/dialogxml/dialogs/pictchoice.hpp, src/game/boe.dlgutil.cpp, src/game/boe.party.cpp
Saw a TODO comment that was trivial to resolve.
Previously: You could click "Cancel" when choosing the graphic for a new PC, but it would create the PC anyway.
Now: You can't click "Cancel" in that situation (which is good because it prevents loss of prior stat choices).
=> remove the cancel button in case where it would be ignored

src/game/boe.consts.hpp, src/game/boe.text.cpp, src/game/boe.text.hpp
The logic that was causing #233 was marked as kludgy and in need of a redo. I've done that, and I think the new logic is more correct.
=> Simplify scary logic around inventory item buttons.

src/game/boe.actions.cpp, src/game/boe.party.cpp, src/game/boe.party.hpp, src/pcedit/pc.action.cpp, src/universe/party.cpp, src/universe/party.hpp
I forgot to have Escape cancel item target mode.
While I'm at it, I want to make identification cancel in advance if there are no unidentified items, and it should end after identifying the last item (as was TODO noted).
=> Cancel item target

src/game/boe.combat.cpp, src/game/boe.combat.hpp, src/game/boe.text.cpp, src/game/boe.text.hpp
This implements a quality of life feature on my checklist https://github.com/NQNStudios/cboe/issues/16
When you try to end outdoor combat and monsters are alive, it prints which ones and how many, preserving the same print order as when the encounter begins, and saving summoned monsters for last.
=> When the player can't end outdoor combat, list living enemies

rsrc/strings/talk-node-descs.txt, src/game/boe.actions.cpp, src/game/boe.dlgutil.cpp, src/game/boe.dlgutil.hpp
I went to make a message print when there are no items available for sale (as suggested in #216 and will fix #216). This wasn't very hard to do.
When a special node starts a shop, it will still display the shop if there are no items. We could change that, too, by printing to the buffer? I don't know if we need to, though.
While implementing this I noticed bug #544 and fixed it (fix #544)
=> Shop change and talk mode fix

rsrc/dialogs/cast-spell.xml, src/dialogxml/dialogs/dialog.cpp, src/game/boe.actions.cpp, src/game/boe.graphics.cpp, src/game/boe.graphics.hpp, src/game/boe.main.cpp, src/game/boe.party.cpp, src/gfx/render_shapes.cpp, src/gfx/render_shapes.hpp, src/gfx/render_text.cpp, src/spell.cpp, src/universe/pc.hpp, test/init.cpp
This makes changes to the spellcasting UI.
* M or P to recast will no longer default to Light or Minor Bless/Minor Heal. You need to cast something before recast becomes available. This fixes #535 and I think it's disorienting when I've just started the game and M casts Light in a town that's fully lit, so the change is generally good I'd say.
* I implemented a recasting hint in the text bar, which was one of the things I mentioned in my quality-of-life checklist https://github.com/NQNStudios/cboe/issues/16. It should move status icons to the left when necessary, to fall between the left text and right text. I think with very long spell names, this could overlap with the text, which would be bad. But I don't know what statuses go in the text bar so I haven't tested/handled that case yet. …
=> Quality of life: Spellcasting

src/fileio/fileio.hpp, src/fileio/fileio_party.cpp, src/game/boe.actions.cpp, src/game/boe.actions.hpp, src/game/boe.main.cpp, src/game/boe.town.cpp, src/game/boe.town.hpp, src/pcedit/pc.action.cpp, src/pcedit/pc.appleevents.mm, src/pcedit/pc.graphics.cpp, src/pcedit/pc.main.cpp, src/pcedit/pc.menus.linux.cpp, src/pcedit/pc.menus.mac.mm, src/pcedit/pc.menus.win.cpp
I discovered #549 while debugging the rest of these issues, so I fixed it first.
I made `debug_leave_town()` call `end_town_mode()` so it does everything that would normally be done when going outdoors, minus handling exit special nodes. That was the fix. (Fix #549)
Issues #204, #267, and #480 were all caused by having duplicated save game logic in many places, which were not all the same. I refactored things so every time you Save or Save As, it follows the same code-path and does everything that it should no matter the context that triggered it.
Fix #204 
Fix #267 
Fix #480 
EDIT: Ah, of course this is gonna break the PC editor, I need to fix that.
=> Fix multiple inconsistencies when saving

src/game/boe.actions.cpp
Tested on Linux. Unconfirmed on MacOS and Windows.
=> Modified the UI redraw order in handle_death() to fix #250 and #558.

rsrc/dialogs/get-num.xml, rsrc/dialogs/help-debug.xml, rsrc/dialogs/select-sector.xml, src/dialogxml/keycodes.cpp, src/dialogxml/keycodes.hpp, src/game/boe.actions.cpp, src/game/boe.actions.hpp, src/game/boe.combat.cpp, src/game/boe.combat.hpp, src/game/boe.main.cpp, src/scenario/outdoors.hpp
I wanted to add a new debug action, and then I wanted to have it automatically appear in the help dialog, and I also wanted the debug help dialog to come up in response to `?` because I never remember it's just `/` for the debug one. And I wanted the help dialogue to just let me pick one since the list is open already.
So I did all that.
Putting all the debug actions into a map the way I've done here, is a pattern we could repeat for ALL keyboard shortcuts, although I don't want to do that work if there's no need to. But it would move us towards the dream of #319.
* Just for fun, you can use the arrow keys to pick a new outdoor section in the scenario editor (this is very nice)
* I made a new debug action: press `%` to fight a wandering encounter from the current section, or press `^` to …
=> Refactor Debug Keys

rsrc/dialogs/edit-talk-node.xml, rsrc/schemas/dialog.xsd, src/dialogxml/widgets/field.cpp, src/dialogxml/widgets/field.hpp, src/scenedit/scen.townout.cpp
This is a more involved change than anything in my other scenedit PR.
I really don't like the way the 2 talk node keys are handled in the editor. Filling the fields with 4 spaces, expecting the designer to delete them and put in 4 other characters... just awkward. Also, 'purc' is impossible to remember and I never will.
New behavior is:
* The fields start out empty, and it is *allowed* to keep *one of them* empty. (A node only needs one key to be useful, right?
* When the node is saved, empty strings are replaced with `"    "`. If this is not harmless to the game logic, then I'll need to make the game aware that either key might be `"    "`.
* You cannot type more than 4 characters in these fields (unless there's a way to insert characters I'm not aware of).
* If you put 'buy' in a field, …
=> Better editing for talk node keys

rsrc/SConscript
I did some experimenting on getting @clort81's ClortSans font into the game.
It turns out that the resource manager had already been updated to support bdf files. The one problem was that Scons would only copy ttf files, so I fixed that, and that should suffice to Fix #229. (Note: they also asked for PCX fonts, but SFML [does not support those](https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Font.php):
> The supported font formats are: TrueType, Type 1, CFF, OpenType, SFNT, X11 PCF, Windows FNT, BDF, PFR and Type 42. Note that this function knows nothing about the standard fonts installed on the user's system, thus you can't load them directly.
Having made that change, I tried loading ClortSans-12 which can be downloaded here: …
=> Scons copy bdf fonts.

src/game/boe.main.cpp, src/pcedit/pc.main.cpp, src/scenedit/scen.core.cpp, src/scenedit/scen.main.cpp, src/tools/winutil.cpp, src/tools/winutil.hpp
This adds a reusable function to launch documentation URLs.
Fix #553 - help button launches terrain type documentation page.
=> Launch terrain type documentation for help button

rsrc/bases/bladbase/items.xml, rsrc/scenarios/busywork/items.xml, rsrc/scenarios/stealth/items.xml, rsrc/scenarios/valleydy/items.xml, rsrc/scenarios/zakhazi/items.xml, test/files/town/townrectUniversal/items.xml, test/replays/scenarios/use-special-terrain/items.xml
See title. Changes the unidentified name for Leather Baldric (which was "Leather Baldri") and fixes a typo in the name of Resurrection Balm (was "Ressurection Balm").
=> Fixed typos for Resurrection Balm and Leather Baldric

doc/documentation.lyx, doc/game/Combat.html, doc/game/Editor.html, doc/game/Mage.html, doc/game/Priest.html, doc/game/Tips.html, rsrc/dialogs/help-combat.xml, rsrc/dialogs/help-magic.xml, rsrc/strings/help.txt, rsrc/strings/mage-spells.txt, rsrc/strings/priest-spells.txt, src/game/boe.party.cpp
I noticed the documentation/spell descriptions use `him/her` which is an awkward grammatical construction. I grepped for that phrase and changed it to `them` everywhere I found.
=> Him/her -> them

src/game/boe.party.cpp, src/scenario/item.cpp
Armor items with item level 0, will have a base defense value of 0 instead of 1, and display their defense value as such in the get items screen.
Fix #245
=> Fix armor level 0

rsrc/dialogs/drop-item-confirm.xml, rsrc/dialogs/edit-sign.xml, rsrc/dialogs/preferences.xml, rsrc/schemas/dialog.xsd, src/dialogxml/dialogs/dialog.cpp, src/dialogxml/widgets/control.cpp, src/dialogxml/widgets/message.cpp, src/doxy/mainpage.md, src/gfx/render_text.cpp, src/gfx/render_text.hpp
This should fix #246 ...
However, it does not, because for some reason, message controls are ignoring their text size. (This goes for the preset sizes that already existed, too.)
=> Fix text size and underline in dialogxml

rsrc/SConscript
From scons builds running `xmllint` we get a *ton* of the same warning message:
https://github.com/calref/cboe/actions/runs/13340575223/job/37264370598#step:4:3334
> /usr/local/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/subprocess.py:1020: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
>  self.stdin = io.open(p2cwrite, 'wb', bufsize)
I don't know what it means, or whether the `bufsize` argument might have an important intended purpose. But removing it gets rid of this warning.
=> fix scons validation warning

proj/vs2013/Common/Common.vcxproj, proj/vs2013/Game/Blades of Exile.vcxproj, proj/vs2013/OBoE Tests/OBoE Tests.vcxproj, proj/vs2013/PcEdit/Char Editor.vcxproj, proj/vs2013/ScenEdit/Scen Editor.vcxproj, proj/vs2017/Blades of Exile.vcxproj, proj/vs2017/Character Editor/Character Editor.vcxproj, proj/vs2017/Common/Common.vcxproj, proj/vs2017/Installer/Installer.vcxproj, proj/vs2017/Scenario Editor/Scenario Editor.vcxproj, proj/vs2017/Tests/Tests.vcxproj
Our Visual Studios builds use vcpkg manifest mode. In CI, this is working, but when manually running the builds from Visual Studio in a new clone, it won't work for a new developer. Each individual project needs to have its properties changed to turn on Manifest mode, and if you forget to do it, the linker errors are unclear and discouraging. I don't want to forget to make this change anymore--so I'm staging the vcxproj changes for it.
Also, VS2013 didn't have Catch/Clara include directories added. Fixed that.
=> Vs manifest mode

src/game/boe.graphutil.cpp, src/game/boe.newgraph.cpp, src/game/boe.newgraph.hpp, src/gfx/render_image.cpp, src/gfx/render_image.hpp, src/location.cpp, src/location.hpp, src/pcedit/pc.main.cpp
I need to keep testing this.
Fix #582 
Fix #97
=> Fix some ranged attack animation bugs

proj/vs2013/OBoE Tests/OBoE Tests.vcxproj.user, proj/vs2017/Tests/Tests.vcxproj.user, test/item_legacy.cpp, test/out_write.cpp, test/town_legacy.cpp
This stages Visual Studio project configuration that makes the tests launch in the correct working directory.
Then it fixes some test crashes that were happening to me locally because of undefined behavior.
I hope it doesn't break the tests on other targets.
=> Fix Visual Studio undefined behavior test errors

rsrc/dialogs/edit-monster.xml, rsrc/dialogs/help-debug.xml, rsrc/dialogs/preview-dialogs-confirm.xml, src/dialogxml/dialogs/dialog.cpp, src/dialogxml/dialogs/dialog.hpp, src/dialogxml/widgets/message.cpp, src/game/boe.actions.cpp, src/game/boe.actions.hpp, src/game/boe.main.cpp
Fix #608
I noticed 'Number of Dice' and 'Number of Sides' texts need to be widened in edit-monster--is that something you're working on or should I push my fix?
=> Fix line breaks being ignored. Fix #608

src/gfx/render_image.cpp, src/gfx/render_shapes.cpp, src/gfx/render_shapes.hpp, src/gfx/render_text.cpp
Fix #86 which was re-opened by the scale-aware text change.
=> Fix shop item highlighted text again

src/game/boe.graphutil.cpp
This change fixes the bug where enemy ranged attacks in peace mode show the player at the wrong position.
I can imagine that it might have unintended consequences--I have *no idea* how many edge cases come across this code path, or why they would want to force the party to appear at the center even if they're not.
Fix #628
=> When party is off-center, draw_party_symbol offset them. Fix #628

src/dialogxml/dialogs/dialog.cpp, src/dialogxml/widgets/control.hpp
I have certain UI expectations, like for the Yes/No dialogs to all respond to both the Y or N key. If there's a default button that responds to Enter, I want it to do that without clobbering its existing hotkey.
Fix #600
=> Default controls keep their hotkey AND the enter key

src/game/boe.party.cpp
Page 2 of the spell picker has always been touch-and-go... I found a new crash today because of trying to assign an LED status to a button which would be hidden on page 2. We simply can say that a PC cannot cast the None spell, to fix this.
=> Fix another crash on page 2 of spell picker

src/universe/living.cpp
There already was a check to prevent this bug. I don't fully understand it.
Changing `>` to `>=` fixes the problem. But does it break these statuses in other contexts?
Fix #138
=> when dumpfound/sleep status is 0 bound low to 0. Fix #138

src/game/boe.newgraph.cpp
Fix #74
According to the text in the editor, a facial picture value of `-1` means use the monster's regular graphic. Default facial pic is used by the editor when placing monsters.
=> -1 is supposed to be no face pic

src/gfx/render_image.cpp, src/gfx/render_text.cpp, src/gfx/render_text.hpp
Fix #651
Here's a fullscreen window mode shown fixed:
=> Fix scaled text offset in fullscreen modes. 

src/fileio/fileio.cpp, src/game/boe.actions.cpp, src/game/boe.actions.hpp, src/game/boe.infodlg.cpp, src/game/boe.infodlg.hpp, src/game/boe.main.cpp, src/game/boe.specials.cpp, src/pcedit/pc.editors.cpp, src/pcedit/pc.main.cpp, src/tools/replay.cpp, src/tools/replay.hpp
A round of replay system fixes and improvements.
* replaying the debug help window was broken in 2 ways which I fixed
* Fix #559 -- When we observe bugs in random sessions, we no longer have to regret that we didn't pass `--record` at the command line. The replay data is kept in memory and writing it out can be enabled with debug action Z.
* Recording replays into the working directory by default is pretty wonky, because the working directory is usually a build output folder that might be clobbered by a `scons -c`, wiping out important replays. Also, if the working directory is the Visual Studio project folder, you end up adding untracked files to your repo folder which can get annoying. So - I've made the default replay directory a folder alongside the tempDir that already exists. On …
=> Replay fixes

src/game/boe.combat.cpp, src/game/boe.combat.hpp, src/game/boe.graphics.cpp
This fixes the rendering of melee damage booms on enemies larger than 1x1. It also doesn't break spell booms (which already worked).
I saw a place to do a refactor which I thought would make it easier to debug this. The fix (in the second commit) could be cherry-picked without the refactor if it looks like I got that wrong.
Fix #127
=> Fix text appearing out of alignment with adjusted booms

src/game/boe.text.cpp, src/game/boe.text.hpp
The Use button for special items draws a Drop button on master. I think I remember the change I made that broke this--and it all stems from the code being confusing (there was a TODO note that this resolves).
=> Fix the Use Special item button.

src/game/boe.actions.cpp, src/game/boe.actions.hpp, src/game/boe.combat.cpp, src/game/boe.main.cpp, src/game/boe.party.cpp, src/game/boe.party.hpp, src/universe/party.cpp
There were a bunch of bugs with Capture Soul/Simulacrum:
* The pick buttons in Simulacrum were not shown/hidden correctly for filled/unfilled slots
* With no captured souls, you would still get a picker dialog
* Monsters exported after leaving a scenario, would cause a crash when you try to summon them
* Loading a save file with captured souls, the slot number of a captured monster would be interpreted as the monster number (so Apprentice Mage (27) in slot 3 would be loaded as Townsperson (3) in slot 0-- the 27 would be dropped and not loaded).
I fixed all of these problems.
I also added a debug action which clears captured souls.
=> Fix simulacrum

src/game/boe.actions.cpp, src/game/boe.main.cpp, src/game/boe.town.cpp, src/global.hpp
- "Finish what you're doing first" comes up a lot in the text buffer. I wanted to add such a message to a new case but couldn't remember how to match the ones that are already in there. Solution: Make it a constant. Also, standardize existing messages so they all prefix with the attempted action.
- The menubar "Do Alchemy" button passing an 'A' key could have unexpected behavior, i.e. in talk mode, clicking "Ask About". Fixed this
- Don't know if the menubar "Wait" button could cause a bug by passing 'w', but fixed the kludge regardless. Also, some code paths of "Wait" would no-op silently. Fixed that.
=> Actions fixes

rsrc/dialogs/help-debug.xml, src/dialogxml/dialogs/dialog.cpp, src/dialogxml/keycodes.cpp, src/game/boe.actions.cpp, src/game/boe.actions.hpp, src/game/boe.graphics.cpp, src/game/boe.main.cpp
* Previewing dialogxmls, don't crash the game if the XML has an error in it (just show the message)
* Allow canceling the file picker for previewing dialogxmls
* Allow toggling debug mode in the startup menu. In the startup menu, you can only use actions that make sense.
* Debug enter town: new behavior - move the party's outdoors location to a town entrance if possible (Fix #664)
* Fix debug help menu crashing when trying to make '~' into a cKey
* Make the debug help window more readily expandible, and add more buttons.
* Note: I still don't want to make it a stupidly tall dialog like the ones we've had to split up to fit on screens when scaled. It shouldn't get much bigger -- maybe it should paginate if it has to. Although, if it bleeds off the screen, at least it won't break players' …
=> Debug actions work

doc/editor/Advanced.html, doc/editor/Contents.html, src/fileio/fileio_scen.cpp, src/global.hpp, src/scenario/scenario.cpp, src/scenario/scenario.hpp, src/scenedit/scen.fileio.cpp, src/scenedit/scen.sdfpicker.cpp, src/scenedit/scen.sdfpicker.hpp, src/universe/party.hpp
This fixes the stack overflow and clarifies the spatial nature of the SDF grid.
Fix #675
=> use nested map for SDF names to save stack space. Fix #674

src/game/boe.text.cpp, src/gfx/render_text.cpp, src/gfx/render_text.hpp
Ever since I added scale-aware text, the About Dialog has looked like this (I didn't notice until recently):
Today I figured out that it's because of something weird with sf::Text and sf::Font. When we change the character size of the text right before rendering it, it doesn't properly prepare all the large-size glyphs that it needs, and many characters get a blank glyph. If I set the character size of the text to the scaled size *before* initializing it with all the other things in win_draw_string(), then we get our glyphs.
=> Set scale-aware text size before initializing the sf::Text object

rsrc/dialogs/ask-save-replay.xml, rsrc/dialogs/debug-crash-confirm.xml, src/dialogxml/keycodes.cpp, src/game/boe.actions.cpp, src/game/boe.actions.hpp, src/game/boe.main.cpp
This one probably needs some discussion and refinement.
The main idea is, if a player finds a crash in the game, I want to capture as much info about it as possible. So this prompts the player to save the replay log and links them to this issue tracker.
Drawback: GitHub doesn't support drag-and-drop for XML files. So players have to zip the XML file themselves. (I think we have a dependency that could do the zipping? But I don't know how to write that code.)
Drawback: GitHub requires an account before adding an issue. It might be more ideal to find an external bug tracker, or host our own portal for it, to remove friction for less technically inclined players.
If any of this sounds undesirable in the core repo, I can also have it be exclusive to Itch edition and point to my fork's issue …
=> On catching fatal error, prompt to save the log and report

src/game/boe.actions.cpp, src/game/boe.dlgutil.cpp, src/game/boe.dlgutil.hpp
In comments on #669 I outlined a way to intuitively handle shopping from a healer if the active PC is fully healed. This PR implements my suggestion. I think it feels pretty good and makes shopping better even outside the case that was buggy before: it's just nice to have the shop cycle between injured PCs if you're trying to buy healing for everyone.
These are the rules:
- If the active PC gets an empty shop, iterate from the first to last PC until finding someone who can see a shop item
- If none can shop, show the 'no item' response
- When the active PC buys something, if this clears out the shop, iterate from the first to last PC until finding someone who can see a shop item
- if none can see an item, stay on the empty shop of the PC that was active when the last item was bought.
- …
=> Don't display 'no item' response if another PC can shop.

rsrc/dialogs/preferences.xml, src/game/boe.combat.cpp, src/game/boe.dlgutil.cpp, src/game/boe.main.cpp, src/game/boe.newgraph.cpp, src/game/boe.newgraph.hpp
Optional feature shifts the screen to place the highest possible number of enemies on screen when targeting ranged attacks.
=> Target lock

src/scenedit/scen.actions.cpp, src/scenedit/scen.graphics.cpp, src/scenedit/scen.graphics.hpp
The first commit makes the editor stop prompting you whether to shift areas after the first time you attempt scrolling out of bounds.
The second commit here is a really gory one. The overall purpose is to make the area-shift prompt more functional when zoomed out. When zoomed out, the editor still tracks a center relative to 1x zoom, which may not match the center of the zoomed-out view. I think this is a good thing, so I preserved it (the prior commit being an important part of that). However, previously, you could scroll to the visual limit of an outdoor section/town view, and yet not be prompted to shift to the next logical area (i.e. town entrance, neighboring outdoor section). You had to keep scrolling until the *technical* center hit its maximum, which felt weird. The new behavior …
=> Scenario editor zoom & area-shift improvements
